import { Inter } from 'next/font/google';
import './globals.css';
import 'animate.css';
import 'material-icons/iconfont/material-icons.css';
import AuthProvider from '../../Components/AuthProvider/AuthProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
